### PR TITLE
added a racial slurs filter to the trpc Petition router

### LINKED ISSUE #6: create hateful language filter on petition signature
Several people have used the n-word as part of their petition signatures. maybe there should be a filter that makes sure signatures don't have that in them before accepting/displaying them. I'd be happy to make a pr for this if you want me to take care of it.

### PR DESCRIPTION
**Pull request by JasonBoyett**
# Basic hate speech filter

some users were leaving racial slurs in the petition. I made a quick filtering mechanism to reject any petition containing racial slurs.

Fixes #6

### Trigger warning the code contains racial slurs
I had to give the filter something to check against so it was kinda unavoidable.

Screenshot from 2024-02-10 08-44-24

### CODE REVIEW

**Comment by ahmadaccino** [comment]
Thanks for the pr, but I think there are better ways to protect against profanity. There are a lot more words people can say than the ones in your list. I'll make a separate update for a profanity filter

**Comment by ahmadaccino** [comment]
I'll accept this for now in case someone feels like putting those words specifically. Then I'll roll out the update later sometime today.

**Comment by JasonBoyett** [comment]
There is a [profanity filtering library on npm.](https://www.npmjs.com/package/leo-profanity) I can use it to make a more robust solution if you don't mind introducing it as a dependency.

**Comment by ahmadaccino** [comment]
Haha thats the one I am adding now. no worries, I also need to add a better way to detect if someone has signed up before, right now people are clearing their localstorage

**Comment by JasonBoyett** [comment]
How about integrating clerk?

**Comment by ahmadaccino** [comment]
I thought about authentication but the idea was to make the barrier to entry as little as possible. A lot of people will avoid a tool if they need to sign in to use it effectively. I recently tried this with [another meme site I made](https://www.bonerbattles.lol/) and I got people that said it was funny but not alot that signed up and put their time.

**Comment by JasonBoyett** [comment]
I guess you could just use cookies?

**Pull request merged**
